models_path: 'src/app/models'
serializers_path: 'src/app/serializers'
migrations_path: 'src/db/migrations'
associations_path: 'src/db/associations.ts'
schema_path: 'src/db/schema.ts'
db_config_path: 'src/conf/env/db.yml'
unit_spec_path: 'spec/unit'
feature_spec_path: 'spec/features'
